### ISSUE TITLE
Damage Broken

### ISSUE THREAD

**Issue by Sandalsdotcom** [ugackMiner53/Mitch-Client#10]
I was trying everything out with the hacks on such as infinite damage and attack speed. I then went into a game with some friends and played normally but I found I do 0-1 damage per hit with anything. I don't know if this is a problem with the cheats or the game.

**Comment by ugackMiner53** [comment]
Duplicate of #3, this is caused by enabling infinite damage and then disabling it. This bug is hard to fix.

**Comment by ugackMiner53** [comment]
Fixed in release [2.1.2](https://github.com/ugackMiner53/Mitch-Client/releases/tag/2.1.2)
