### ISSUE TITLE
Delete Client?

### ISSUE THREAD

**Issue by WoahKenny** [ugackMiner53/Mitch-Client#14]
How do I delete the client? I can't find the file anywhere .

**Comment by ugackMiner53** [comment]
Simply search for "Add or Remove Programs" in system settings, and in that menu, search for "Mitch Client". Click on it, and there should be an uninstall button there. Click it, and an uninstaller should pop up.

==IGNORE THE BELOW PART IF THE ABOVE STEPS WORKS==

If you installed it some weird way other than the easy installer, then you have to go to your Muck folder, and delete the following folders/files:
BepInEx
winhttp.dll
doorstop_config.ini
