### ISSUE TITLE
Can you put it into mac

### ISSUE THREAD

**Issue by Pixelcon18** [ugackMiner53/Mitch-Client#25]
I have a mac and cannot use this so please can you turn it into a mac supported thing

**Comment by Spiderfffun** [comment]
Try using a VM. If you know how to set up one, it works well, and if you dont search it up.

**Comment by ugackMiner53** [comment]
You should be able to use the zip download and manually install it. I do not know how to create installers for mac, plus the more "locked down" natures of macs makes it harder to install programs.
