### ISSUE TITLE
Change the infinite damage toggle its either infinite or nothing

### ISSUE THREAD

**Issue by terriermon42Q** [ugackMiner53/Mitch-Client#3]
toggleing to 1 attack is not fun

**Comment by ugackMiner53** [comment]
This is difficult to fix, as the script modifies the damage of the weapon itself. It can be fixed by storing the damage in a variable, or just dropping the weapon and picking it back up

**Comment by Thebostongamer** [comment]
Even after dropping I still deal 1dmg

**Comment by deadfish768** [comment]
bro can u plz fix this problem is so annoying I need to use one-hit kill to be able to kill anything

**Comment by Sandalsdotcom** [comment]
> This is difficult to fix, as the script modifies the damage of the weapon itself. It can be fixed by storing the damage in a variable, or just dropping the weapon and picking it back up

The dropping weapon thing didn't work but the variable storage did.

**Comment by deadfish768** [comment]
> 
> 
> > This is difficult to fix, as the script modifies the damage of the weapon itself. It can be fixed by storing the damage in a variable, or just dropping the weapon and picking it back up
> 
> The dropping weapon thing didn't work but the variable storage did.

if u modifaied it can i plz have the modified ver?

**Comment by SneakyFlamingo** [comment]
even restarting the game doesnt fix it ): i cant even kill a single mob... Also, how do you store damage inside a variable?

**Comment by SneakyFlamingo** [comment]
Its not even fixed by reinstalling the game. I uninstalled the client and then it worked fine, but when i redownloaded it bugged out again.

**Comment by Sandalsdotcom** [comment]
> Its not even fixed by reinstalling the game. I uninstalled the client and then it worked fine, but when i redownloaded it bugged out again.

yeah I tried that too what I'm doing right now is taking this hack but modifying everything and adding more. I will have to ask UgackMiner53 for permission to share that.

**Comment by ugackMiner53** [comment]
Fixed in release [2.1.2](https://github.com/ugackMiner53/Mitch-Client/releases/tag/2.1.2)
