### ISSUE TITLE
help how do i even do this thing

### ISSUE THREAD

**Issue by Axtr0** [ugackMiner53/Mitch-Client#6]
i downloaded it and stuff and now i dont know what to do help me pls [jerma sus face]

**Comment by ugackMiner53** [comment]
When you download the .zip from the releases tab, you then open steam, go to Muck, click on the little settings wheel, and hit "Manage", and then "Browse Local Files". It should open File Explorer with files such as "Muck.exe" and "Muck_Data". Simply extract the contents of the zip into the folder, and start Muck with steam. You can check if Mitch has loaded by going to the "About" page, and it should state that you are using Mitch Client.

An easier alternative installer is currently being worked on so you do not have to worry about this.

**Comment by ugackMiner53** [comment]
Fixed in version [2.1.0](https://github.com/ugackMiner53/Mitch-Client/releases/tag/2.1.0) with the installer
