### ISSUE TITLE
I extract the file inside the muck.exe and muck_data folder but it isnt working 

### ISSUE THREAD

**Issue by Murugan47** [ugackMiner53/Mitch-Client#7]
![image](https://user-images.githubusercontent.com/85506027/121090637-e121dc00-c7b6-11eb-9744-7ab686a95b01.png)

**Comment by ugackMiner53** [comment]
... that is the source, which can be used for creating you own version. When the instructions state to download the zip, it meant the "Mitch-Client.zip" This can be found in the [releases](https://github.com/ugackMiner53/Mitch-Client/releases) tab. The download code button is for code. I recommend you download and use the new installer there.
