### ISSUE TITLE
Hacks cant let you type

### ISSUE THREAD

**Issue by ToppatLeader** [ugackMiner53/Mitch-Client#8]
When i was in a server with my friend and i was tpying with him i pressed the key to TP to a player while tpying, and i teleported to him. I told him it was a bug that had happened to me before. So PLEASE make the hack dont work while tpying.

Thanks!

**Comment by ugackMiner53** [comment]
Thank you for letting me know. I will get to work on this ASAP

**Comment by ugackMiner53** [comment]
Fixed in version 2.1.1

**Comment by ToppatLeader** [comment]
Thank you!!!
